# Generated by Django 3.2.9 on 2021-11-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='highlighted',
        ),
    ]
