# Generated by Django 3.2.9 on 2021-11-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todouser',
            options={'verbose_name': 'TodoUser', 'verbose_name_plural': 'TodoUsers'},
        ),
        migrations.AlterField(
            model_name='todouser',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='email',
            field=models.EmailField(max_length=20, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Prefer not to say', 'no_preference')], max_length=20),
        ),
    ]
